apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 2  # Set the desired number of replicas
  selector:
    matchLabels:
      app: node-app
  template: 
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: deepch98/node-app:latest
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3