apiVersion: v1
kind: Service
metadata:
  name: node-app-service-clusterip
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80  # Expose the service on port 80 within the cluster
      targetPort: 3000  # Forward traffic to port 3000 on the pods
  type: ClusterIP
