apiVersion: v1
kind: Service
metadata:
  name: node-app-service-nodeport
spec:
  selector:
    app: node-app
  ports:
    - protocol: TCP
      port: 80  # Expose the service on port 80 on each Node
      targetPort: 3000  # Forward traffic to port 3000 on the pods
  type: NodePort
